<?php
<p><hr><hc>1 </hc> <hc><aref='43374968  .php'>43374968  </hc> <hc>ACHO</hc> <hc>RIOS</hc> <hc>NIMIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>2 </hc> <hc><aref='10198993  .php'>10198993  </hc> <hc>ACOSTA</hc> <hc>QUISPE</hc> <hc>PAUL HENRY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>3 </hc> <hc><aref='06740033  .php'>06740033  </hc> <hc>ACUÑA</hc> <hc>BERROSPI</hc> <hc>ALEX</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>4 </hc> <hc><aref='22502265  .php'>22502265  </hc> <hc>AGUILAR</hc> <hc>LAGUNA</hc> <hc>ASTRID</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>5 </hc> <hc><aref='32987729  .php'>32987729  </hc> <hc>AGUILAR</hc> <hc>PAREDES</hc> <hc>ERNESTO DARWIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>6 </hc> <hc><aref='00838529  .php'>00838529  </hc> <hc>AGUILAR</hc> <hc>RUIZ</hc> <hc>EZSEQUIEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>7 </hc> <hc><aref='40377484  .php'>40377484  </hc> <hc>AGUIRRE</hc> <hc>QUINTANILLA</hc> <hc>MERLE MILAGROS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>8 </hc> <hc><aref='07143360  .php'>07143360  </hc> <hc>ALARCON</hc> <hc>MORE</hc> <hc>MODESTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>9 </hc> <hc><aref='07809580  .php'>07809580  </hc> <hc>ALAYZA</hc> <hc>ARIAS</hc> <hc>MANUEL ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='43881278  .php'>43881278  </hc> <hc>ALBARRAN</hc> <hc>MEDINA</hc> <hc>ELVIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='18067237  .php'>18067237  </hc> <hc>ALBITRES</hc> <hc>INFANTES</hc> <hc>JHONNY JAVIER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='41349511  .php'>41349511  </hc> <hc>ALBUJAR</hc> <hc>DE LA CRUZ</hc> <hc>MARIA MALENA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='27074721  .php'>27074721  </hc> <hc>ALCANTARA</hc> <hc>BOZA</hc> <hc>FRANCISCO ALEJANDRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='32899961  .php'>32899961  </hc> <hc>ALEGRE</hc> <hc>CALDERON</hc> <hc>LUIS ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='06095016  .php'>06095016  </hc> <hc>ALFARO</hc> <hc>PALACIOS DE HUAITA</hc> <hc>EDITH BETTY</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='19850381  .php'>19850381  </hc> <hc>ALIAGA</hc> <hc>ROTA</hc> <hc>LUIS ANTONIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='09638521  .php'>09638521  </hc> <hc>ALVA</hc> <hc>PALOMARES</hc> <hc>GLADIA MARIBEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='17831799  .php'>17831799  </hc> <hc>ALVA</hc> <hc>PRETEL</hc> <hc>ROSSIO DEL PILAR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='10680956  .php'>10680956  </hc> <hc>ALVARADO</hc> <hc>VIZCARDO</hc> <hc>BETSY ROCIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='41185035  .php'>41185035  </hc> <hc>AMBROSIO</hc> <hc>GARCIA</hc> <hc>GIULLIANA PATRICIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='41809938  .php'>41809938  </hc> <hc>AMBULAY</hc> <hc>BRICEÑO</hc> <hc>JOHNNY PERCY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='09763452  .php'>09763452  </hc> <hc>ANAYA</hc> <hc>RAYMUNDO</hc> <hc>MARIO ANTONIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='43925029  .php'>43925029  </hc> <hc>ANCAJIMA</hc> <hc>TIMANA</hc> <hc>JUAN CARLOS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='42457051  .php'>42457051  </hc> <hc>ANDIA</hc> <hc>VILCAPOMA</hc> <hc>DAVID HERNAN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='40706670  .php'>40706670  </hc> <hc>ANGULO</hc> <hc>VALDIVIA</hc> <hc>RAFAEL MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='22406535  .php'>22406535  </hc> <hc>ANTONIO</hc> <hc>BASILIO</hc> <hc>DORILA TEODOSIA</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='25552563  .php'>25552563  </hc> <hc>AQUISSE</hc> <hc>TORRES</hc> <hc>TEODORO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='07197659  .php'>07197659  </hc> <hc>ARANIBAR</hc> <hc>RIVERO</hc> <hc>RUTH MILAGROS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='10283796  .php'>10283796  </hc> <hc>ARASHIRO</hc> <hc>TAMASHIRO</hc> <hc>ANA CECILIA</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='06785270  .php'>06785270  </hc> <hc>ARAUZO</hc> <hc>RAMIREZ</hc> <hc>GIOVANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='07739006  .php'>07739006  </hc> <hc>ARELLANO</hc> <hc>CABO</hc> <hc>MARIETTA ZORAIDA SOCORRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='08578047  .php'>08578047  </hc> <hc>ARIAS</hc> <hc>MARCOS</hc> <hc>ADA GRABIELA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='10585743  .php'>10585743  </hc> <hc>ARIAS</hc> <hc>PALOMINO</hc> <hc>MARCO ANTONIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='21289640  .php'>21289640  </hc> <hc>ARIAS</hc> <hc>RIMARI</hc> <hc>ELIANA MARIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='44105190  .php'>44105190  </hc> <hc>ARRUNATEGUI</hc> <hc>SALDARRIAGA</hc> <hc>SILVER ANDRES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='08569906  .php'>08569906  </hc> <hc>ASPILCUETA</hc> <hc>PEREZ</hc> <hc>CRISTOBAL URIEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='07501770  .php'>07501770  </hc> <hc>AYALA</hc> <hc>CALDERON</hc> <hc>KRISTHIAN OLIVER</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='02848481  .php'>02848481  </hc> <hc>AYALA</hc> <hc>DIAZ</hc> <hc>MARCOS AQUILES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='06783487  .php'>06783487  </hc> <hc>AYUDANTE</hc> <hc>RELAIZA</hc> <hc>ELIZABETH</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='43991476  .php'>43991476  </hc> <hc>AZCONA</hc> <hc>AVALOS</hc> <hc>GUISELLA IVONNE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='42109759  .php'>42109759  </hc> <hc>AZULA</hc> <hc>DIAZ</hc> <hc>HENRY EDILBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='09853135  .php'>09853135  </hc> <hc>BALLENA</hc> <hc>DOMINGUEZ</hc> <hc>VICTOR GIOVANNY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='09549434  .php'>09549434  </hc> <hc>BALTODANO</hc> <hc>DIAZ</hc> <hc>RAUL IVAN</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='20006543  .php'>20006543  </hc> <hc>BALVIN</hc> <hc>EGAS</hc> <hc>EFRAIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>45</hc> <hc><aref='08584551  .php'>08584551  </hc> <hc>BARNETT</hc> <hc>GUILLEN</hc> <hc>LIDA ESTHER</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>46</hc> <hc><aref='10621491  .php'>10621491  </hc> <hc>BASTO</hc> <hc>MUÑOZ</hc> <hc>ROSA LILIANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>47</hc> <hc><aref='40611601  .php'>40611601  </hc> <hc>BASUALDO</hc> <hc>LOPEZ</hc> <hc>ELIAS IVAN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>48</hc> <hc><aref='00160971  .php'>00160971  </hc> <hc>BECERRA</hc> <hc>GARCIA</hc> <hc>DANIEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>49</hc> <hc><aref='08271469  .php'>08271469  </hc> <hc>BECERRA</hc> <hc>PALOMINO</hc> <hc>CARLOS ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>50</hc> <hc><aref='000105841 .php'>000105841 </hc> <hc>BENITO</hc> <hc>RODRIGUEZ</hc> <hc>JOSE ANTONIO</hc> <hc>ESPAÑA</hc> <hc>Ordinario Principal</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>51</hc> <hc><aref='09854795  .php'>09854795  </hc> <hc>BERMUDEZ</hc> <hc>TAPIA</hc> <hc>MANUEL ALEXIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>52</hc> <hc><aref='000332855 .php'>000332855 </hc> <hc>BIDINOST</hc> <hc>.</hc> <hc>PAOLO</hc> <hc>ITALIA</hc> <hc>Ordinario Principal</hc> <hc>Dedicacion Exclusiva</hc> </hr></p>
<p><hr><hc>53</hc> <hc><aref='25629280  .php'>25629280  </hc> <hc>BIO</hc> <hc>GAIDOLFI</hc> <hc>CARLA MARIA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>54</hc> <hc><aref='25746345  .php'>25746345  </hc> <hc>BIO</hc> <hc>GAIDOLFI</hc> <hc>FAUSTO MICHELE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>55</hc> <hc><aref='07796524  .php'>07796524  </hc> <hc>BLAS</hc> <hc>MONTENEGRO</hc> <hc>LUZ PETRONILA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>56</hc> <hc><aref='000044710 .php'>000044710 </hc> <hc>BOLIS</hc> <hc>.</hc> <hc>GIAN BATTISTA FAUSTO</hc> <hc>ITALIA</hc> <hc>Ordinario Principal</hc> <hc>Dedicacion Exclusiva</hc> </hr></p>
<p><hr><hc>57</hc> <hc><aref='21448115  .php'>21448115  </hc> <hc>BOZA</hc> <hc>OLAECHEA</hc> <hc>MARGARITA LUISA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>58</hc> <hc><aref='10530728  .php'>10530728  </hc> <hc>BRAVO</hc> <hc>LOPEZ</hc> <hc>NATALY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>59</hc> <hc><aref='08080775  .php'>08080775  </hc> <hc>BRAVO</hc> <hc>SAENZ</hc> <hc>WALTER ALEJANDRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>60</hc> <hc><aref='000367365 .php'>000367365 </hc> <hc>BRIOZZO</hc> <hc>PEREYRA</hc> <hc>MARIA TERESA</hc> <hc>ITALIA</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>61</hc> <hc><aref='40723640  .php'>40723640  </hc> <hc>BUENDIA</hc> <hc>ROMERO</hc> <hc>CESAR ANTONIO</hc> <hc>ESPAÑA</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>62</hc> <hc><aref='07747856  .php'>07747856  </hc> <hc>BURGA</hc> <hc>GUTIERREZ</hc> <hc>ROSA MARIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>63</hc> <hc><aref='40067119  .php'>40067119  </hc> <hc>BURGOS</hc> <hc>BASTIDAS</hc> <hc>ANGIE ROMY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>64</hc> <hc><aref='15746875  .php'>15746875  </hc> <hc>CABALLERO</hc> <hc>CANTU</hc> <hc>JOSE JEREMIAS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>65</hc> <hc><aref='09869377  .php'>09869377  </hc> <hc>CABANILLAS</hc> <hc>ROJAS</hc> <hc>WILLIAM EUGENIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>66</hc> <hc><aref='08947396  .php'>08947396  </hc> <hc>CABELLO</hc> <hc>TORRES</hc> <hc>RITA JAQUELINE</hc> <hc>ESPAÑA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>67</hc> <hc><aref='06456480  .php'>06456480  </hc> <hc>CACERES</hc> <hc>URBINA</hc> <hc>HILDA YOLANDA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>68</hc> <hc><aref='19857956  .php'>19857956  </hc> <hc>CALIXTO</hc> <hc>ALIAGA</hc> <hc>SILVIO GUSTAVO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>69</hc> <hc><aref='29587019  .php'>29587019  </hc> <hc>CALLE</hc> <hc>CHEJE</hc> <hc>YURI HOLSIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>70</hc> <hc><aref='08667250  .php'>08667250  </hc> <hc>CAMARENA</hc> <hc>ARESTEGUI</hc> <hc>JHON JHONY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>71</hc> <hc><aref='42658184  .php'>42658184  </hc> <hc>CAMINO</hc> <hc>RIVERA</hc> <hc>CRISTIAN ENMANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>72</hc> <hc><aref='80278308  .php'>80278308  </hc> <hc>CAPUÑAY</hc> <hc>GONZALES</hc> <hc>MARIA LIDIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>73</hc> <hc><aref='04304833  .php'>04304833  </hc> <hc>CARDENAS</hc> <hc>CABEZAS</hc> <hc>JESUS MEDALIT</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>74</hc> <hc><aref='08665105  .php'>08665105  </hc> <hc>CARDENAS</hc> <hc>LEDESMA</hc> <hc>BLUIDSON PABLO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>75</hc> <hc><aref='10735921  .php'>10735921  </hc> <hc>CARRASCAL</hc> <hc>VIZARRETA</hc> <hc>URSULA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>76</hc> <hc><aref='09982771  .php'>09982771  </hc> <hc>CARRASCO</hc> <hc>LOPEZ</hc> <hc>ILIANOV PABLO</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>77</hc> <hc><aref='09339841  .php'>09339841  </hc> <hc>CARREÑO</hc> <hc>MARTINEZ</hc> <hc>JUAN ELIAS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>78</hc> <hc><aref='15612175  .php'>15612175  </hc> <hc>CARREÑO</hc> <hc>ROLDAN</hc> <hc>ALBERTO DANILO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>79</hc> <hc><aref='15744138  .php'>15744138  </hc> <hc>CASTAÑEDA</hc> <hc>CHIRRE</hc> <hc>ELVIRA TEOFILA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>80</hc> <hc><aref='06188898  .php'>06188898  </hc> <hc>CASTAÑEDA</hc> <hc>RAMIREZ</hc> <hc>CESAR WALTER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>81</hc> <hc><aref='00163075  .php'>00163075  </hc> <hc>CASTILLA</hc> <hc>CRUZ</hc> <hc>HILARIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>82</hc> <hc><aref='41648542  .php'>41648542  </hc> <hc>CASTILLO</hc> <hc>GUTIERREZ</hc> <hc>GIANCARLO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>83</hc> <hc><aref='08124577  .php'>08124577  </hc> <hc>CASTILLO</hc> <hc>PICHEN</hc> <hc>SEGUNDO CESAR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>84</hc> <hc><aref='15601765  .php'>15601765  </hc> <hc>CASTRO</hc> <hc>BARTOLOME</hc> <hc>HECTOR JORGE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>85</hc> <hc><aref='06962611  .php'>06962611  </hc> <hc>CASTRO</hc> <hc>MEDINA</hc> <hc>MAXIMILIANA IRENE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>86</hc> <hc><aref='45473955  .php'>45473955  </hc> <hc>CECILIANO</hc> <hc>CAMONES</hc> <hc>SHIRLEY KARINA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>87</hc> <hc><aref='10207235  .php'>10207235  </hc> <hc>CERON</hc> <hc>SALAZAR</hc> <hc>NORMA JULIETA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>88</hc> <hc><aref='17615559  .php'>17615559  </hc> <hc>CESPEDES</hc> <hc>PANDURO</hc> <hc>BERNARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>89</hc> <hc><aref='17561750  .php'>17561750  </hc> <hc>CESPEDES</hc> <hc>PANDURO</hc> <hc>JACOBA DEL PILAR</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>90</hc> <hc><aref='17634166  .php'>17634166  </hc> <hc>CESPEDES</hc> <hc>PANDURO</hc> <hc>SUGEIT EMPERATRIZ</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>91</hc> <hc><aref='08500622  .php'>08500622  </hc> <hc>CHAVEZ</hc> <hc>BARCES</hc> <hc>MARIA ELENA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>92</hc> <hc><aref='09883255  .php'>09883255  </hc> <hc>CHAVEZ</hc> <hc>MEDRANO</hc> <hc>VICTOR RICARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>93</hc> <hc><aref='09893536  .php'>09893536  </hc> <hc>CHAVEZ</hc> <hc>NORABUENA</hc> <hc>KARINA JUDITH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>94</hc> <hc><aref='09140700  .php'>09140700  </hc> <hc>CHAVEZ</hc> <hc>PRADO</hc> <hc>ANGELICA MARITZA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>95</hc> <hc><aref='08470274  .php'>08470274  </hc> <hc>CHAVEZ</hc> <hc>VEGA</hc> <hc>CARLOS</hc> <hc>ARGENTINA</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>96</hc> <hc><aref='08185119  .php'>08185119  </hc> <hc>CHINCHA</hc> <hc>ALVAREZ</hc> <hc>ANA MARIA NINOSHKA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>97</hc> <hc><aref='03317072  .php'>03317072  </hc> <hc>CHIROQUE</hc> <hc>FLORES</hc> <hc>VICTOR MANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>98</hc> <hc><aref='40664123  .php'>40664123  </hc> <hc>CHIROQUE</hc> <hc>VELASQUEZ</hc> <hc>GRISEL VIOLETA</hc> <hc>CHILE</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>99</hc> <hc><aref='06157624  .php'>06157624  </hc> <hc>CHONG</hc> <hc>CENTURION</hc> <hc>ERNESTO GALVARINO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='02434440  .php'>02434440  </hc> <hc>CHURA</hc> <hc>GOMEZ</hc> <hc>CESAR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='09673277  .php'>09673277  </hc> <hc>CISNEROS</hc> <hc>AYALA</hc> <hc>CLAUDIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='08732585  .php'>08732585  </hc> <hc>CJAHUA</hc> <hc>HUANACHI</hc> <hc>ZITA SILVIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='40343126  .php'>40343126  </hc> <hc>CLAROS</hc> <hc>SANTIAGO</hc> <hc>CARLOS EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='41376156  .php'>41376156  </hc> <hc>COLAN</hc> <hc>VALLADARES</hc> <hc>CESAR EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='08042573  .php'>08042573  </hc> <hc>COLLAZOS</hc> <hc>GUTIERREZ</hc> <hc>ADELMA ELIZABETH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='000420096 .php'>000420096 </hc> <hc>CONTINI</hc> <hc>.</hc> <hc>GIULIANA</hc> <hc>ITALIA</hc> <hc>Ordinario Principal</hc> <hc>Dedicacion Exclusiva</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='07743259  .php'>07743259  </hc> <hc>CONTRERAS</hc> <hc>FLORES</hc> <hc>WALTER PEDRO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='09983907  .php'>09983907  </hc> <hc>CORAL</hc> <hc>YGNACIO</hc> <hc>MARCO ANTONIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>10</hc> <hc><aref='16647035  .php'>16647035  </hc> <hc>CORDOVA</hc> <hc>SALCEDO</hc> <hc>FELIMON DOMINGO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='21444290  .php'>21444290  </hc> <hc>CORONADO</hc> <hc>SANTILLAN</hc> <hc>LUIS AUGUSTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='21060243  .php'>21060243  </hc> <hc>CORONEL</hc> <hc>QUINTEROS</hc> <hc>EDITH MARIA</hc> <hc>BOLIVIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='08569923  .php'>08569923  </hc> <hc>CORTEZ</hc> <hc>MONDRAGON</hc> <hc>CESAR SEGUNDO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='10063247  .php'>10063247  </hc> <hc>COSTA</hc> <hc>RODRIGUEZ</hc> <hc>JORGE EDUARDO</hc> <hc>ITALIA</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='40580884  .php'>40580884  </hc> <hc>COZ</hc> <hc>CONTRERAS</hc> <hc>SOFIA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='06807083  .php'>06807083  </hc> <hc>COZ</hc> <hc>CONTRERAS</hc> <hc>VANESA CAROLINA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='08780148  .php'>08780148  </hc> <hc>CRISTOBAL</hc> <hc>VELASQUEZ</hc> <hc>DORIS HILDA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='06660409  .php'>06660409  </hc> <hc>CRUZ</hc> <hc>ACUÑA</hc> <hc>EDGAR ODON</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='40113161  .php'>40113161  </hc> <hc>CRUZADO</hc> <hc>MELENDEZ</hc> <hc>MELINA ROXANA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>11</hc> <hc><aref='41414387  .php'>41414387  </hc> <hc>DAVALOS</hc> <hc>ARCA</hc> <hc>JOSEPH KENNETH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='22423025  .php'>22423025  </hc> <hc>DAVILA</hc> <hc>LAGUNA</hc> <hc>RONALD FERNANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='08519098  .php'>08519098  </hc> <hc>DAVILA</hc> <hc>TAPIA</hc> <hc>JOSE VICENTE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='07681903  .php'>07681903  </hc> <hc>DE LA CRUZ</hc> <hc>CAMACO</hc> <hc>DANTE PEDRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='08707499  .php'>08707499  </hc> <hc>DE LA ROSA</hc> <hc>VALVERDE</hc> <hc>CECILIA MELCHORA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='08737456  .php'>08737456  </hc> <hc>DE LA ROSA</hc> <hc>VALVERDE</hc> <hc>PEDRO LUIS ENRIQUE</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='07760676  .php'>07760676  </hc> <hc>DEL BUSTO</hc> <hc>BRETONECHE</hc> <hc>RAFAEL MARTIN</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='07764635  .php'>07764635  </hc> <hc>DEL BUSTO</hc> <hc>BRETONECHE</hc> <hc>RAUL ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='07876526  .php'>07876526  </hc> <hc>DEL CAMPO</hc> <hc>GAYTAN</hc> <hc>TEOBALDO JULIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='41296093  .php'>41296093  </hc> <hc>DELGADO</hc> <hc>HEREDIA</hc> <hc>ELIAS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>12</hc> <hc><aref='10738430  .php'>10738430  </hc> <hc>DIAZ</hc> <hc>DIAZ</hc> <hc>LILIANA</hc> <hc>ESPAÑA</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='10301350  .php'>10301350  </hc> <hc>DIAZ</hc> <hc>GERVASI</hc> <hc>GIOVANI MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='15693637  .php'>15693637  </hc> <hc>DIAZ</hc> <hc>NONATO</hc> <hc>MIGUEL ALCIDES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='40074376  .php'>40074376  </hc> <hc>DIAZ</hc> <hc>PARDAVE</hc> <hc>MIGUEL ANGEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='10603883  .php'>10603883  </hc> <hc>DIAZ</hc> <hc>VARGAS</hc> <hc>SELENI ADILIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='07149775  .php'>07149775  </hc> <hc>DOMINGUEZ</hc> <hc>JARA</hc> <hc>ALICIO VICTOR</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='07847018  .php'>07847018  </hc> <hc>DUCOS</hc> <hc>CASAS</hc> <hc>TEODORICO JESUS ADOLFO ST</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='15607816  .php'>15607816  </hc> <hc>ECHEGARAY</hc> <hc>ROMERO</hc> <hc>HECTOR ORLANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='09887433  .php'>09887433  </hc> <hc>EGOAVIL</hc> <hc>DE LA CRUZ</hc> <hc>CARLOS HUGO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='08581718  .php'>08581718  </hc> <hc>ELESCANO</hc> <hc>CORDOVA</hc> <hc>WILFREDO CLEMENTE</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>13</hc> <hc><aref='10000717  .php'>10000717  </hc> <hc>ENCISO</hc> <hc>ZAVALA</hc> <hc>FAUSTA ISABEL</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='80224089  .php'>80224089  </hc> <hc>ENRIQUE</hc> <hc>CORDOVA</hc> <hc>ELBERT</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='29533833  .php'>29533833  </hc> <hc>ENRIQUEZ</hc> <hc>CACERES</hc> <hc>MANUEL IGNACIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='001067402 .php'>001067402 </hc> <hc>ENRIQUEZ</hc> <hc>CANTO</hc> <hc>YORDANIS</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='44369968  .php'>44369968  </hc> <hc>ERAZO</hc> <hc>CAMACHO</hc> <hc>MILTON ROYER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='18170287  .php'>18170287  </hc> <hc>ESPINOLA</hc> <hc>MARIÑOS</hc> <hc>WILDER ALEX</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='08042574  .php'>08042574  </hc> <hc>ESPINOZA</hc> <hc>ALATA</hc> <hc>REYNALDO VICTOR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='21134423  .php'>21134423  </hc> <hc>ESTARES</hc> <hc>PORRAS</hc> <hc>OMAR EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='32544407  .php'>32544407  </hc> <hc>FARFAN</hc> <hc>ZEGARRA</hc> <hc>HAROLD MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='32543625  .php'>32543625  </hc> <hc>FERNANDEZ</hc> <hc>CARDOZA</hc> <hc>JANET DEL ROSARIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>14</hc> <hc><aref='09600036  .php'>09600036  </hc> <hc>FERNANDEZ</hc> <hc>CONDORI</hc> <hc>ROXANA CARLA</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='42153498  .php'>42153498  </hc> <hc>FERNANDEZ</hc> <hc>CRUZ</hc> <hc>EMILIANO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='40962158  .php'>40962158  </hc> <hc>FERNANDEZ</hc> <hc>MONTEMAYOR</hc> <hc>VERONICA INES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='21133103  .php'>21133103  </hc> <hc>FERNANDEZ</hc> <hc>SUASNABAR</hc> <hc>SELENA CELESTE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='10683741  .php'>10683741  </hc> <hc>FIGUEROA</hc> <hc>ANAMARIA</hc> <hc>JORGE HUGO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='08612078  .php'>08612078  </hc> <hc>FLORES</hc> <hc>BALLESTEROS</hc> <hc>TEODORO EMILIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='08039505  .php'>08039505  </hc> <hc>FLORES</hc> <hc>MORALES</hc> <hc>JORGE ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='09854418  .php'>09854418  </hc> <hc>FLORES</hc> <hc>ORTEGA</hc> <hc>YESSIKA GRAYA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='06859230  .php'>06859230  </hc> <hc>FLORES</hc> <hc>PALOMINO</hc> <hc>FLORESMILO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='17611959  .php'>17611959  </hc> <hc>FONSECA</hc> <hc>RIVERA</hc> <hc>IRMA CAROLINA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>15</hc> <hc><aref='41291740  .php'>41291740  </hc> <hc>FRANCO</hc> <hc>DEL CASTILLO</hc> <hc>GLORIA NADIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='07708918  .php'>07708918  </hc> <hc>FUENTES</hc> <hc>SUPANTA DE FUKUNAGA</hc> <hc>NORMA</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='40660826  .php'>40660826  </hc> <hc>GAGO</hc> <hc>RODRIGO</hc> <hc>KATIA ELVA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='09607929  .php'>09607929  </hc> <hc>GALINDO</hc> <hc>GONZALES</hc> <hc>TANIA DEL CARMEN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='43253292  .php'>43253292  </hc> <hc>GAMARRA</hc> <hc>CUEVA</hc> <hc>ALEXANDER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='000834605 .php'>000834605 </hc> <hc>GAMBATESA</hc> <hc>.</hc> <hc>RUGGIERO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='32860015  .php'>32860015  </hc> <hc>GARCES</hc> <hc>DIAZ</hc> <hc>VICTOR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='10818578  .php'>10818578  </hc> <hc>GARCIA</hc> <hc>MASIAS</hc> <hc>JESSICA VANESSA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='07722412  .php'>07722412  </hc> <hc>GARCIA</hc> <hc>REGAL</hc> <hc>RAUL FRANCISCO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='09781789  .php'>09781789  </hc> <hc>GARCIA</hc> <hc>ROJAS</hc> <hc>VIDAL SATURNINO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>16</hc> <hc><aref='06914150  .php'>06914150  </hc> <hc>GARCIA</hc> <hc>ROJAS</hc> <hc>YRMA DORIS</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='15727139  .php'>15727139  </hc> <hc>GARCIA</hc> <hc>SUSANO</hc> <hc>MARITZA GIOVANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='05256191  .php'>05256191  </hc> <hc>GARCIA</hc> <hc>TRIGOZO</hc> <hc>JOSE ABEL</hc> <hc>ITALIA</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='06889871  .php'>06889871  </hc> <hc>GARCIA</hc> <hc>VILCAPOMA</hc> <hc>GLADYS HORTENCIA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='09635561  .php'>09635561  </hc> <hc>GASTELLO</hc> <hc>MATHEWS</hc> <hc>WILLY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='10117155  .php'>10117155  </hc> <hc>GOMERO</hc> <hc>ESPINOZA</hc> <hc>CLARA ROSIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='09630967  .php'>09630967  </hc> <hc>GONZAGA</hc> <hc>ESPINOZA</hc> <hc>MARIA NELLY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='10683679  .php'>10683679  </hc> <hc>GONZALES</hc> <hc>ANAMPA</hc> <hc>LUIS OMAR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='43667732  .php'>43667732  </hc> <hc>GONZALES</hc> <hc>CALLE</hc> <hc>FREDY ABELARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='47017231  .php'>47017231  </hc> <hc>GONZALES</hc> <hc>CONTRERAS</hc> <hc>NORMA DE LOS MILAGROS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>17</hc> <hc><aref='00165739  .php'>00165739  </hc> <hc>GONZALES</hc> <hc>COTRINA</hc> <hc>JULIO CESAR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='21135050  .php'>21135050  </hc> <hc>GONZALES</hc> <hc>QUISPE</hc> <hc>HUMBERTO FERNANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='09486797  .php'>09486797  </hc> <hc>GONZALEZ</hc> <hc>FARFAN</hc> <hc>MARIA EUGENIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='06269543  .php'>06269543  </hc> <hc>GONZALEZ</hc> <hc>SAENZ</hc> <hc>MODESTA MARIA ADELA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='25426710  .php'>25426710  </hc> <hc>GOYBURU</hc> <hc>MOLINA DE GOMEZ</hc> <hc>MARLENE ESTHER</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='00860188  .php'>00860188  </hc> <hc>GRANDEZ</hc> <hc>PORTOCARRERO</hc> <hc>AUGUSTO MARINO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='07556886  .php'>07556886  </hc> <hc>GUEVARA</hc> <hc>LOPEZ</hc> <hc>HERLINDA ESTELA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='10284099  .php'>10284099  </hc> <hc>GUTIERREZ</hc> <hc>ASCARZA</hc> <hc>LUZ YOLANDA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='10280181  .php'>10280181  </hc> <hc>GUTIERREZ</hc> <hc>AZCARZA</hc> <hc>DORIS EDITH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='23946287  .php'>23946287  </hc> <hc>GUTIERREZ</hc> <hc>BUSTAMANTE</hc> <hc>SILVIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>18</hc> <hc><aref='08798497  .php'>08798497  </hc> <hc>GUTIERREZ</hc> <hc>CASTILLO</hc> <hc>MARIO ANTONIO</hc> <hc>PERÚ</hc> <hc>Ordinario Principal</hc> <hc>Dedicacion Exclusiva</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='06957981  .php'>06957981  </hc> <hc>GUTIERREZ</hc> <hc>PUSARI</hc> <hc>JUSTINIANO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='10727756  .php'>10727756  </hc> <hc>HERNANDEZ</hc> <hc>PINO</hc> <hc>GIOVANA LOURDES</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='44008733  .php'>44008733  </hc> <hc>HERNANDEZ</hc> <hc>VASQUEZ</hc> <hc>ERICK BRANDUZ</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='40660575  .php'>40660575  </hc> <hc>HERRERA</hc> <hc>CONCHA</hc> <hc>RENAN ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='06775252  .php'>06775252  </hc> <hc>HIDALGO</hc> <hc>GOMEZ</hc> <hc>ALFONSO GREGORIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='09905355  .php'>09905355  </hc> <hc>HUAMAN</hc> <hc>GUTIERREZ</hc> <hc>JOSE MANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='10454580  .php'>10454580  </hc> <hc>HUAMAN</hc> <hc>GUTIERREZ</hc> <hc>OSCAR GUSTAVO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='44127158  .php'>44127158  </hc> <hc>HUAPAYA</hc> <hc>PARDAVE</hc> <hc>RICHARD JOAO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='16170336  .php'>16170336  </hc> <hc>HUIMAN</hc> <hc>SANDOVAL</hc> <hc>JOSE ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>19</hc> <hc><aref='42643059  .php'>42643059  </hc> <hc>HURTADO</hc> <hc>MERINO</hc> <hc>ALBERTO ZACARIAS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='10735796  .php'>10735796  </hc> <hc>IBERICO</hc> <hc>CHAVEZ</hc> <hc>ROLANDO RAMIRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='46532718  .php'>46532718  </hc> <hc>IMAN</hc> <hc>MORAN</hc> <hc>ANGHELA MIRELLA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='08646807  .php'>08646807  </hc> <hc>INCA</hc> <hc>BAZAN</hc> <hc>FERNANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='08396132  .php'>08396132  </hc> <hc>INFANTES</hc> <hc>SANTILLAN</hc> <hc>EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='43089939  .php'>43089939  </hc> <hc>IZQUIERDO</hc> <hc>HERNANDEZ</hc> <hc>DENIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='07589826  .php'>07589826  </hc> <hc>JARA</hc> <hc>ASENCIOS DE MENDOZA</hc> <hc>IRMA VICTORIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='09304104  .php'>09304104  </hc> <hc>KCOMT</hc> <hc>CHUCAN DE MUJICA</hc> <hc>OLINDA ROXANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='09626330  .php'>09626330  </hc> <hc>KUONG</hc> <hc>MERIK</hc> <hc>MIGUEL ANGEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='15736641  .php'>15736641  </hc> <hc>LA ROSA</hc> <hc>BENEDICTO</hc> <hc>CARLOS GIOVANI</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>20</hc> <hc><aref='07961578  .php'>07961578  </hc> <hc>LA ROSA</hc> <hc>BOTONERO</hc> <hc>JAVIER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='02689556  .php'>02689556  </hc> <hc>LABAN</hc> <hc>ELERA</hc> <hc>VICTOR TEODORO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='40376829  .php'>40376829  </hc> <hc>LAFOSSE</hc> <hc>MASIAS</hc> <hc>JORGE LUIS</hc> <hc>ITALIA</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='42548764  .php'>42548764  </hc> <hc>LAGOS</hc> <hc>LIBERATO</hc> <hc>DAVID</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='41494750  .php'>41494750  </hc> <hc>LALUPU</hc> <hc>VALLADOLID</hc> <hc>JOSE HUMBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='40438250  .php'>40438250  </hc> <hc>LARCO</hc> <hc>AGUILAR</hc> <hc>AMADA VICTORIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='06121782  .php'>06121782  </hc> <hc>LASTARRIA</hc> <hc>ZAPATA</hc> <hc>JOSE ALEJANDRO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='42362708  .php'>42362708  </hc> <hc>LAURENCIO</hc> <hc>LUNA</hc> <hc>MANUEL ISMAEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='10734053  .php'>10734053  </hc> <hc>LECETA</hc> <hc>GOBITZ</hc> <hc>ROSSINA ALDA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='41658689  .php'>41658689  </hc> <hc>LEONARDO</hc> <hc>RAMOS</hc> <hc>MILAGROS ELISA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>21</hc> <hc><aref='000754989 .php'>000754989 </hc> <hc>LEYTON</hc> <hc>CARDENAS</hc> <hc>CARLOS ALBERTO</hc> <hc>COLOMBIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='07924964  .php'>07924964  </hc> <hc>LIMONCHI</hc> <hc>CANALES</hc> <hc>ITALO ALDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='07282807  .php'>07282807  </hc> <hc>LINO</hc> <hc>QUICAÑA</hc> <hc>HECTOR JOSE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='03110339  .php'>03110339  </hc> <hc>LIZANO</hc> <hc>CARMEN</hc> <hc>LAZARO ELIAS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='21087618  .php'>21087618  </hc> <hc>LOBATO</hc> <hc>CALDERON</hc> <hc>GODOFREDO ROMAN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='06674117  .php'>06674117  </hc> <hc>LOPEZ</hc> <hc>AVILES</hc> <hc>NESTOR MANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='000380761 .php'>000380761 </hc> <hc>LOPEZ</hc> <hc>BRAVO</hc> <hc>RODOLFO ODLANIER</hc> <hc>CHILE</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='08153969  .php'>08153969  </hc> <hc>LOPEZ</hc> <hc>BULNES</hc> <hc>JORGE LUIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='08584920  .php'>08584920  </hc> <hc>LOPEZ</hc> <hc>DEL MAR</hc> <hc>JOEL BENIGNO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='00373720  .php'>00373720  </hc> <hc>LOPEZ</hc> <hc>REQUENA</hc> <hc>JUAN EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>22</hc> <hc><aref='09639954  .php'>09639954  </hc> <hc>LUNA</hc> <hc>MIRANDA</hc> <hc>RAUL</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='10157753  .php'>10157753  </hc> <hc>LUNA</hc> <hc>RAMIREZ</hc> <hc>EDITH NORMA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='15723552  .php'>15723552  </hc> <hc>LUNA</hc> <hc>SANTOS</hc> <hc>JUAN CARLOS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='09392792  .php'>09392792  </hc> <hc>LUY</hc> <hc>MONTEJO</hc> <hc>CARLOS AUGUSTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='15612229  .php'>15612229  </hc> <hc>MACEDO</hc> <hc>BARRERA</hc> <hc>EUFEMIO MAGNO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='000057480 .php'>000057480 </hc> <hc>MAGGI</hc> <hc>.</hc> <hc>GUIDO EUGENIO MARIO</hc> <hc>ITALIA</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='06217919  .php'>06217919  </hc> <hc>MAGUIÑA</hc> <hc>MENDOZA</hc> <hc>MARIO ARTURO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='08740729  .php'>08740729  </hc> <hc>MANRIQUE</hc> <hc>PINO</hc> <hc>OSCAR</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='25620629  .php'>25620629  </hc> <hc>MARQUINA</hc> <hc>MAUNY</hc> <hc>WILFREDO JAVIER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='43272586  .php'>43272586  </hc> <hc>MAS</hc> <hc>CARO</hc> <hc>NIXON LUIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>23</hc> <hc><aref='25739572  .php'>25739572  </hc> <hc>MASCELLARO</hc> <hc>LUPERDI</hc> <hc>GIANCARLO ENZO PASCQUALE</hc> <hc>ITALIA</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='09607876  .php'>09607876  </hc> <hc>MASGO</hc> <hc>LARA</hc> <hc>LUIS ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='09697998  .php'>09697998  </hc> <hc>MATHEUS</hc> <hc>ROMERO</hc> <hc>JORGE HERNANDO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='10613109  .php'>10613109  </hc> <hc>MATTA</hc> <hc>SANTIVAÑEZ</hc> <hc>KARINA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='40935708  .php'>40935708  </hc> <hc>MAZA</hc> <hc>CHUMPITAZ</hc> <hc>ANGELA GIOVANA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='32983656  .php'>32983656  </hc> <hc>MEDINA</hc> <hc>INFANTE</hc> <hc>MAGALY BETZABE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='40517760  .php'>40517760  </hc> <hc>MEDINA</hc> <hc>PEREZ</hc> <hc>MARIA YOVANI</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='25791096  .php'>25791096  </hc> <hc>MEDINA</hc> <hc>SIRLOPU</hc> <hc>MARTHA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='25634361  .php'>25634361  </hc> <hc>MELGAREJO</hc> <hc>SALAZAR</hc> <hc>MARGARITA GLADYS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='23978854  .php'>23978854  </hc> <hc>MENDOZA</hc> <hc>CABALLERO</hc> <hc>WILFREDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>24</hc> <hc><aref='08308467  .php'>08308467  </hc> <hc>MENDOZA</hc> <hc>NAVARRO</hc> <hc>AIDA LUZ</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='10246770  .php'>10246770  </hc> <hc>MENENDEZ</hc> <hc>MUERAS</hc> <hc>ROSA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='01051153  .php'>01051153  </hc> <hc>MERA</hc> <hc>NAVAL</hc> <hc>HUGO JAIME</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='07969037  .php'>07969037  </hc> <hc>MERINO</hc> <hc>ZEVALLOS</hc> <hc>CARLOS ANTONIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='23842285  .php'>23842285  </hc> <hc>MESTAS</hc> <hc>VALERO</hc> <hc>ROGER MANUEL</hc> <hc>BRASIL</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='00838777  .php'>00838777  </hc> <hc>MINGA</hc> <hc>SARMIENTO</hc> <hc>ROLANDO NOLVERTHY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='25697416  .php'>25697416  </hc> <hc>MITTA</hc> <hc>CURAY</hc> <hc>EVER RAMIRO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='40894989  .php'>40894989  </hc> <hc>MOISES</hc> <hc>GONZALES</hc> <hc>NORMA ROCIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='03688780  .php'>03688780  </hc> <hc>MONDRAGON</hc> <hc>LIMA</hc> <hc>MARITZA ELIZABETH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='10271073  .php'>10271073  </hc> <hc>MONTERROSO</hc> <hc>CORONADO</hc> <hc>CESAR ANTONIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>25</hc> <hc><aref='08633219  .php'>08633219  </hc> <hc>MONTES</hc> <hc>VILLANUEVA</hc> <hc>NILDA DORIS</hc> <hc>BRASIL</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='09994755  .php'>09994755  </hc> <hc>MONTOYA</hc> <hc>SALDAÑA</hc> <hc>SILVIA MARIANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='02841777  .php'>02841777  </hc> <hc>MONTOYA</hc> <hc>TEJADA</hc> <hc>WILSON EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='21521372  .php'>21521372  </hc> <hc>MOQUILLAZA</hc> <hc>CASTILLA</hc> <hc>JORGE LUIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='16717938  .php'>16717938  </hc> <hc>MORA</hc> <hc>CUMPA</hc> <hc>LUIS ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='42007303  .php'>42007303  </hc> <hc>MORALES</hc> <hc>ROJAS</hc> <hc>WILLIAM ANTONY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='40064308  .php'>40064308  </hc> <hc>MORALES</hc> <hc>VASQUEZ</hc> <hc>CESAR ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='08500743  .php'>08500743  </hc> <hc>MORENO</hc> <hc>CUEVA</hc> <hc>MAXIMO ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='21133559  .php'>21133559  </hc> <hc>MORENO</hc> <hc>PALOMINO</hc> <hc>JEAN PAUL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='19870721  .php'>19870721  </hc> <hc>MUCHA</hc> <hc>MONTOYA</hc> <hc>RUTH HAYDEE</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>26</hc> <hc><aref='20662522  .php'>20662522  </hc> <hc>MUNIVE</hc> <hc>JAUREGUI</hc> <hc>HONORIO ELOY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='23851049  .php'>23851049  </hc> <hc>MUÑIZ</hc> <hc>PAUCARMAYTA</hc> <hc>ABEL ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='08269783  .php'>08269783  </hc> <hc>MUÑOZ</hc> <hc>MARTICORENA</hc> <hc>WILLIAM AMADEO</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='15761830  .php'>15761830  </hc> <hc>MUÑOZ</hc> <hc>QUICHIZ</hc> <hc>JAVIER ANGEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='09738114  .php'>09738114  </hc> <hc>MUÑOZ</hc> <hc>TORRE</hc> <hc>HERLINDA MARLENI</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='10230085  .php'>10230085  </hc> <hc>MURILLO</hc> <hc>PONTE</hc> <hc>RICARDO VICTOR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='09593605  .php'>09593605  </hc> <hc>NAUPARI</hc> <hc>CASTILLO</hc> <hc>HEROINA DINA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='06145294  .php'>06145294  </hc> <hc>NAVARRO</hc> <hc>GUERRERO</hc> <hc>TITO RICARDO</hc> <hc>CHILE</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='41438407  .php'>41438407  </hc> <hc>NAVARRO</hc> <hc>LINARES</hc> <hc>JANINA DEL ROCIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='07517476  .php'>07517476  </hc> <hc>NAVARRO</hc> <hc>MONTEAGUDO</hc> <hc>CARMEN CECILIA</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>27</hc> <hc><aref='07626510  .php'>07626510  </hc> <hc>NAVARRO</hc> <hc>VILCHEZ</hc> <hc>IGOR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='09952010  .php'>09952010  </hc> <hc>NEYRA</hc> <hc>DE LA ROSA</hc> <hc>LUIS</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='09936559  .php'>09936559  </hc> <hc>NEYRA</hc> <hc>DE LA ROSA</hc> <hc>NILDRE GERALDINE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='06902484  .php'>06902484  </hc> <hc>NOLAZCO</hc> <hc>VICENTE</hc> <hc>LUIS ARTURO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='09377701  .php'>09377701  </hc> <hc>NUÑEZ</hc> <hc>MANRIQUE</hc> <hc>ANA MARIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='08820367  .php'>08820367  </hc> <hc>NUÑEZ</hc> <hc>SOTO</hc> <hc>LUIS GUILLERMO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='41110999  .php'>41110999  </hc> <hc>OLIVA</hc> <hc>NAVARRO</hc> <hc>JORGE ALEJANDRO</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='07729635  .php'>07729635  </hc> <hc>OLIVARES</hc> <hc>LLONA</hc> <hc>EDUARDO EDMUNDO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='08763051  .php'>08763051  </hc> <hc>ORE</hc> <hc>RIVAS</hc> <hc>RAUL JAVIER</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='08095469  .php'>08095469  </hc> <hc>ORTIZ</hc> <hc>DUCLOS</hc> <hc>JUAN CARLOS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>28</hc> <hc><aref='08801690  .php'>08801690  </hc> <hc>OTSU</hc> <hc>NAVARRETE</hc> <hc>GRACIELA RAQUEL</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='41670439  .php'>41670439  </hc> <hc>OVALLE</hc> <hc>FERNANDEZ</hc> <hc>ALEXIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='41786787  .php'>41786787  </hc> <hc>PACAYA</hc> <hc>DIAZ</hc> <hc>DARINKA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='000080198 .php'>000080198 </hc> <hc>PACCOSI</hc> <hc>.</hc> <hc>GIOVANNI</hc> <hc>ITALIA</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='06851633  .php'>06851633  </hc> <hc>PACCOTAIPE</hc> <hc>ESPINOZA</hc> <hc>SALOME</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='15760945  .php'>15760945  </hc> <hc>PACIFICO</hc> <hc>SOTO</hc> <hc>CARLOS DELFIN</hc> <hc>ARGENTINA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='32543302  .php'>32543302  </hc> <hc>PALACIOS</hc> <hc>FARFAN</hc> <hc>PEDRO MIGUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='03376528  .php'>03376528  </hc> <hc>PALOMINO</hc> <hc>VALDEZ</hc> <hc>MARIA ISABEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='40010019  .php'>40010019  </hc> <hc>PANIZZA</hc> <hc>RICHERO</hc> <hc>LINO MARIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='15859960  .php'>15859960  </hc> <hc>PAREDES</hc> <hc>AGUIRRE</hc> <hc>FREDY ROMAN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>29</hc> <hc><aref='08677518  .php'>08677518  </hc> <hc>PAREDES</hc> <hc>SERRANO</hc> <hc>MARIA SALOME</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='07735674  .php'>07735674  </hc> <hc>PAREJA</hc> <hc>FERNANDEZ</hc> <hc>ANA CECILIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='40511186  .php'>40511186  </hc> <hc>PASCUAL</hc> <hc>MENDOZA</hc> <hc>EDISSON PEDRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='000812857 .php'>000812857 </hc> <hc>PASTEN</hc> <hc>MONARDEZ</hc> <hc>JUAN IGNACIO</hc> <hc>CHILE</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='42750570  .php'>42750570  </hc> <hc>PASTRANA</hc> <hc>BANDAN</hc> <hc>JESSICA MIRIAM</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='21814639  .php'>21814639  </hc> <hc>PECEROS</hc> <hc>ARIAS</hc> <hc>IRMA ROXANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='10144128  .php'>10144128  </hc> <hc>PERALTA</hc> <hc>VERA</hc> <hc>JUAN CARLOS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='41925884  .php'>41925884  </hc> <hc>PERALTA</hc> <hc>VILLANUEVA</hc> <hc>JENNY MAGALY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='08661070  .php'>08661070  </hc> <hc>PEREYRA</hc> <hc>ROMERO</hc> <hc>FLOR DE MARIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='09843721  .php'>09843721  </hc> <hc>PEREZ</hc> <hc>ESTRELLA</hc> <hc>EPIFANIA EULOGIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>30</hc> <hc><aref='08805048  .php'>08805048  </hc> <hc>PEREZ</hc> <hc>FERNANDEZ</hc> <hc>JOSE HIGINIO</hc> <hc>PERÚ</hc> <hc>Ordinario Principal</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='40292729  .php'>40292729  </hc> <hc>PEREZ</hc> <hc>PEREZ</hc> <hc>ITALA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='25777787  .php'>25777787  </hc> <hc>PEREZ</hc> <hc>RODRIGUEZ</hc> <hc>RUTH EVELY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='01323959  .php'>01323959  </hc> <hc>PINAZO</hc> <hc>HERENCIA</hc> <hc>RENE ALFREDO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='07119662  .php'>07119662  </hc> <hc>PINEDA</hc> <hc>LEON</hc> <hc>ROBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='01152072  .php'>01152072  </hc> <hc>PINEDO</hc> <hc>CANTA</hc> <hc>JUAN JOSE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='21564297  .php'>21564297  </hc> <hc>PINEDO</hc> <hc>FERNANDEZ</hc> <hc>MARINA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='07671136  .php'>07671136  </hc> <hc>PINTO</hc> <hc>TORPOCO</hc> <hc>ALBERTO DONALD</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='21086869  .php'>21086869  </hc> <hc>PIZARRO</hc> <hc>PUENTE</hc> <hc>ARTURO LEONEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='09435661  .php'>09435661  </hc> <hc>POLO</hc> <hc>PUELLES</hc> <hc>JOSE MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>31</hc> <hc><aref='08268827  .php'>08268827  </hc> <hc>PONCE</hc> <hc>VEGA</hc> <hc>LUIS ALBERTO</hc> <hc>ESTADOS UNIDOS</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='05295151  .php'>05295151  </hc> <hc>POQUIOMA</hc> <hc>RODRIGUEZ</hc> <hc>ANGEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='44081022  .php'>44081022  </hc> <hc>PORRAS</hc> <hc>CARDENAS</hc> <hc>OSCAR DANIEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='25478348  .php'>25478348  </hc> <hc>POZO</hc> <hc>CCASANI</hc> <hc>ZOSIMO REGULO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='08460860  .php'>08460860  </hc> <hc>PRIVAT</hc> <hc>MARAVI</hc> <hc>LUZ MERCEDES</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='09451560  .php'>09451560  </hc> <hc>PUERTAS</hc> <hc>PORRAS</hc> <hc>MARIA ELIZABETH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='08070278  .php'>08070278  </hc> <hc>QUEVEDO</hc> <hc>DIOSES</hc> <hc>VICTOR ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='10342134  .php'>10342134  </hc> <hc>QUEZADA</hc> <hc>MURGA</hc> <hc>DANIEL</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='06650975  .php'>06650975  </hc> <hc>QUINTEROS</hc> <hc>CAMACHO</hc> <hc>NORMA LUZ</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='33240483  .php'>33240483  </hc> <hc>QUIÑONES</hc> <hc>CORDOVA</hc> <hc>BIDELMINA MARUJA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>32</hc> <hc><aref='08703120  .php'>08703120  </hc> <hc>QUIROZ</hc> <hc>AVILES</hc> <hc>LUIS NAPOLEON</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='10183687  .php'>10183687  </hc> <hc>RAMIREZ</hc> <hc>ARELLANO</hc> <hc>MIGUEL ANGEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='40053375  .php'>40053375  </hc> <hc>RAMOS</hc> <hc>NIÑO NEIRA</hc> <hc>ANA MARIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='44380747  .php'>44380747  </hc> <hc>RAMOS</hc> <hc>PEREZ</hc> <hc>ERICK WILLIAMS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='43437043  .php'>43437043  </hc> <hc>RAMOS</hc> <hc>ROMERO</hc> <hc>MIGUEL FERNANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='09739932  .php'>09739932  </hc> <hc>RAMOS</hc> <hc>TORREJON</hc> <hc>REYNA TEODOSIA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='15678673  .php'>15678673  </hc> <hc>RESPICIO</hc> <hc>LOPEZ</hc> <hc>LUIS ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='08528049  .php'>08528049  </hc> <hc>RIOS</hc> <hc>CUELLAR</hc> <hc>HUMBERTO MOISES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='09799606  .php'>09799606  </hc> <hc>RIOS</hc> <hc>MANRIQUE</hc> <hc>ELVIS ROLDAN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='09994223  .php'>09994223  </hc> <hc>RIOS</hc> <hc>VARGAS</hc> <hc>JORGE MARCELL</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>33</hc> <hc><aref='17896043  .php'>17896043  </hc> <hc>RIVERA</hc> <hc>CALLE</hc> <hc>HUMBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='06613176  .php'>06613176  </hc> <hc>RIVERA</hc> <hc>ROMERO</hc> <hc>DAVID SOSIMO</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='41729686  .php'>41729686  </hc> <hc>RODAS</hc> <hc>MARTINEZ</hc> <hc>RICARDO SALOMON</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='10236949  .php'>10236949  </hc> <hc>RODRIGUEZ</hc> <hc>ALVITES</hc> <hc>ALINA PATRICIA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='10551660  .php'>10551660  </hc> <hc>RODRIGUEZ</hc> <hc>CASTILLO</hc> <hc>EDITH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='06801095  .php'>06801095  </hc> <hc>RODRIGUEZ</hc> <hc>ENCALADA</hc> <hc>JOSE ALEJANDRO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='18222946  .php'>18222946  </hc> <hc>RODRIGUEZ</hc> <hc>ESPINOZA</hc> <hc>RONALD FERNANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='07821253  .php'>07821253  </hc> <hc>RODRIGUEZ</hc> <hc>ITURRI</hc> <hc>ROGER RAFAEL ESTANISLAO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='15739966  .php'>15739966  </hc> <hc>RODRIGUEZ</hc> <hc>NUÑEZ</hc> <hc>JOSE LUIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='31652355  .php'>31652355  </hc> <hc>RODRIGUEZ</hc> <hc>PEREZ</hc> <hc>LUIS EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>34</hc> <hc><aref='02808952  .php'>02808952  </hc> <hc>RODRIGUEZ</hc> <hc>SANDOVAL</hc> <hc>JOSE MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='10725778  .php'>10725778  </hc> <hc>ROJAS</hc> <hc>ARAMBURU</hc> <hc>MAGALLY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='00821693  .php'>00821693  </hc> <hc>ROJAS</hc> <hc>YGLESIAS</hc> <hc>EDUARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='40949739  .php'>40949739  </hc> <hc>ROMERO</hc> <hc>LEYTON</hc> <hc>CLAUDIA LISSETH</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='07522448  .php'>07522448  </hc> <hc>ROSALES</hc> <hc>PACHECO</hc> <hc>ALDO HORACIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='25655141  .php'>25655141  </hc> <hc>RUBIO</hc> <hc>APONTE</hc> <hc>JULIO CESAR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='03367079  .php'>03367079  </hc> <hc>RUIDIAS</hc> <hc>JUAREZ</hc> <hc>MARINA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='10150044  .php'>10150044  </hc> <hc>RUIZ</hc> <hc>CCANCCE</hc> <hc>JOSE VICTOR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='03376948  .php'>03376948  </hc> <hc>RUIZ</hc> <hc>ESPINOZA</hc> <hc>DORIS VIOLETA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='09729256  .php'>09729256  </hc> <hc>RUIZ</hc> <hc>JANGE</hc> <hc>BERTHA MARCELINA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>35</hc> <hc><aref='06960251  .php'>06960251  </hc> <hc>RUIZ</hc> <hc>JANJE</hc> <hc>ALEJANDRO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='40661636  .php'>40661636  </hc> <hc>RUIZ</hc> <hc>RAFAEL</hc> <hc>JORGE LUIS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='25809384  .php'>25809384  </hc> <hc>RUIZ</hc> <hc>RUIZ</hc> <hc>GUADALUPE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='00818283  .php'>00818283  </hc> <hc>RUIZ</hc> <hc>VALLES</hc> <hc>RUBEN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='08363244  .php'>08363244  </hc> <hc>SAAVEDRA</hc> <hc>CHIU</hc> <hc>ROXANA MARGARITA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='42915862  .php'>42915862  </hc> <hc>SAAVEDRA</hc> <hc>MUÑOZ</hc> <hc>NESTOR</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='15609778  .php'>15609778  </hc> <hc>SALAS</hc> <hc>RAMIREZ</hc> <hc>CARLOS MANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='08195765  .php'>08195765  </hc> <hc>SALAZAR</hc> <hc>RIOS</hc> <hc>ROBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='26952199  .php'>26952199  </hc> <hc>SANCHEZ</hc> <hc>ACOSTA</hc> <hc>JUAN SANTIAGO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='08203119  .php'>08203119  </hc> <hc>SANCHEZ</hc> <hc>ARAUJO</hc> <hc>JUAN BAUTISTA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>36</hc> <hc><aref='42135945  .php'>42135945  </hc> <hc>SANCHEZ</hc> <hc>DIAZ</hc> <hc>JHON</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='10352458  .php'>10352458  </hc> <hc>SANCHEZ</hc> <hc>SEGOVIA</hc> <hc>KARLA ROCCIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='40484791  .php'>40484791  </hc> <hc>SANCHEZ</hc> <hc>TORRES</hc> <hc>HEIDI ISABEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='09273004  .php'>09273004  </hc> <hc>SANCHEZ</hc> <hc>VILCARINO</hc> <hc>JORGE DEMETRIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='08181918  .php'>08181918  </hc> <hc>SANDOVAL</hc> <hc>LOZANO</hc> <hc>GIOVANI</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='08180998  .php'>08180998  </hc> <hc>SANDOVAL</hc> <hc>LOZANO</hc> <hc>SERGIO ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='08031444  .php'>08031444  </hc> <hc>SEMINARIO</hc> <hc>OLORTIGUE</hc> <hc>PABLO HUGO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='08017508  .php'>08017508  </hc> <hc>SEMINARIO</hc> <hc>OLORTIGUE</hc> <hc>RAUL MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='001242418 .php'>001242418 </hc> <hc>SFREGOLA</hc> <hc>.</hc> <hc>CARMELA</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='42258333  .php'>42258333  </hc> <hc>SICCHA</hc> <hc>VALDERRAMA</hc> <hc>TERESA MILAGROS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>37</hc> <hc><aref='07936807  .php'>07936807  </hc> <hc>SIDIA</hc> <hc>CARRASCO</hc> <hc>MIGUEL JOSE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='08229291  .php'>08229291  </hc> <hc>SOLARI</hc> <hc>DE LA FUENTE</hc> <hc>LUIS MARIA SANTIAGO EDUAR</hc> <hc>PERÚ</hc> <hc>Ordinario Principal</hc> <hc>Dedicacion Exclusiva</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='26601922  .php'>26601922  </hc> <hc>SOLIS</hc> <hc>CESPEDES</hc> <hc>PEDRO ANIBAL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='09452164  .php'>09452164  </hc> <hc>SOTO</hc> <hc>CANALES</hc> <hc>PEDRO PASCUAL</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='40536407  .php'>40536407  </hc> <hc>SOTO</hc> <hc>CCOICCA</hc> <hc>KAROL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='29538510  .php'>29538510  </hc> <hc>SOTO</hc> <hc>COCHON</hc> <hc>CARLINA ROXANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='21076557  .php'>21076557  </hc> <hc>SOTO</hc> <hc>PORRAS</hc> <hc>JESUS GERARDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='09886713  .php'>09886713  </hc> <hc>SUELDO</hc> <hc>VEGA</hc> <hc>GREMY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='09978369  .php'>09978369  </hc> <hc>TACUNAN</hc> <hc>BONIFACIO</hc> <hc>SANTIAGO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='09732261  .php'>09732261  </hc> <hc>TAIPE</hc> <hc>AYLAS</hc> <hc>MARIA DEL CARMEN</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>38</hc> <hc><aref='09363458  .php'>09363458  </hc> <hc>TAPIA</hc> <hc>NUÑEZ</hc> <hc>LOURDES CECILIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='45829609  .php'>45829609  </hc> <hc>TARRILLO</hc> <hc>VILLEGAS</hc> <hc>ANA MARIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='43252024  .php'>43252024  </hc> <hc>TEJADA</hc> <hc>FARFAN</hc> <hc>ANDREA GIULIANA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='07757302  .php'>07757302  </hc> <hc>TEJADA</hc> <hc>RIVAS</hc> <hc>ROBERTO ANTONIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='10177764  .php'>10177764  </hc> <hc>TELLO</hc> <hc>BENITES</hc> <hc>JESSICA VICTORIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='06282789  .php'>06282789  </hc> <hc>TELLO</hc> <hc>MARZOL</hc> <hc>JACQUELINE ANGELICA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='15605059  .php'>15605059  </hc> <hc>TELLO</hc> <hc>PANDAL</hc> <hc>NILO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='07585542  .php'>07585542  </hc> <hc>TENORIO</hc> <hc>MENDEZ</hc> <hc>WALTER ORLANDO</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='21082550  .php'>21082550  </hc> <hc>TIRADO</hc> <hc>PUCUHUAYLA</hc> <hc>JUAN ANTONIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='09639466  .php'>09639466  </hc> <hc>TOLENTINO</hc> <hc>ZAPATA</hc> <hc>JUAN MANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>39</hc> <hc><aref='07786573  .php'>07786573  </hc> <hc>TORO</hc> <hc>DEXTRE</hc> <hc>ELISEO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='42824306  .php'>42824306  </hc> <hc>TREJO</hc> <hc>SARE</hc> <hc>JENNY EVELYN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='10140056  .php'>10140056  </hc> <hc>TRUJILLO</hc> <hc>CHAVEZ</hc> <hc>DELSY MARIELA</hc> <hc>ALEMANIA</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='03568079  .php'>03568079  </hc> <hc>TUME</hc> <hc>CHINCHAY</hc> <hc>LUIS FELIPE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='03494013  .php'>03494013  </hc> <hc>TUME</hc> <hc>RUIZ</hc> <hc>JUAN MANUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='02860918  .php'>02860918  </hc> <hc>UBILLUS</hc> <hc>SILVA</hc> <hc>RUBEN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='17970143  .php'>17970143  </hc> <hc>UCAÑAN</hc> <hc>LEYTON</hc> <hc>ROGER EUGENIO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='08600005  .php'>08600005  </hc> <hc>URBANO</hc> <hc>CHAVEZ</hc> <hc>ANGELICA EULALIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='10272670  .php'>10272670  </hc> <hc>URIBE</hc> <hc>PORRAS</hc> <hc>CARLOS ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='21796501  .php'>21796501  </hc> <hc>VALDIVIA</hc> <hc>ARENAS</hc> <hc>CARMEN ROSA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>40</hc> <hc><aref='07424538  .php'>07424538  </hc> <hc>VALDIVIA</hc> <hc>TORRES</hc> <hc>AUGUSTO GILTTER</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='09223783  .php'>09223783  </hc> <hc>VALDIVIA</hc> <hc>ZUÑIGA</hc> <hc>MARIBEL EMILIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='01046752  .php'>01046752  </hc> <hc>VARGAS</hc> <hc>ROJAS</hc> <hc>JUAN ORLANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='00129361  .php'>00129361  </hc> <hc>VASQUEZ</hc> <hc>BALAREZO</hc> <hc>JOVITA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='40348999  .php'>40348999  </hc> <hc>VASQUEZ</hc> <hc>CASTAÑEDA</hc> <hc>MARIA LUISA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='16562688  .php'>16562688  </hc> <hc>VASQUEZ</hc> <hc>MEDINA</hc> <hc>PEDRO JAMES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='09442181  .php'>09442181  </hc> <hc>VASSALLO</hc> <hc>FERNANDEZ</hc> <hc>LUIGI EDGARDO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='08607374  .php'>08607374  </hc> <hc>VEGA</hc> <hc>BALDEON</hc> <hc>AGUSTIN HEBERT</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='10684755  .php'>10684755  </hc> <hc>VEJARANO</hc> <hc>INGAR</hc> <hc>MANUEL JESUS</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='07238797  .php'>07238797  </hc> <hc>VELARDE</hc> <hc>FLORES</hc> <hc>RUBEN ANTONIO</hc> <hc>ITALIA</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>41</hc> <hc><aref='42071960  .php'>42071960  </hc> <hc>VELASQUEZ</hc> <hc>ESPINOZA</hc> <hc>MONICA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='08172294  .php'>08172294  </hc> <hc>VELASQUEZ</hc> <hc>RODRIGUEZ</hc> <hc>NORMA CONSTANZA</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='10400322  .php'>10400322  </hc> <hc>VELASQUEZ</hc> <hc>ROSAS DE CUTIMBO</hc> <hc>JULIA GLADYS</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='40715884  .php'>40715884  </hc> <hc>VELIZ</hc> <hc>PAREDES</hc> <hc>GUILLERMO RENZO</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='41283752  .php'>41283752  </hc> <hc>VENEGAS</hc> <hc>CAMPOS</hc> <hc>MIRIAM ISABEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='08725896  .php'>08725896  </hc> <hc>VERGARA</hc> <hc>PALACIOS</hc> <hc>GLADYS ELIDA</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='10777769  .php'>10777769  </hc> <hc>VERGARA</hc> <hc>TRUJILLO</hc> <hc>JULIO DOUGLAS</hc> <hc>ITALIA</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='07503079  .php'>07503079  </hc> <hc>VICUÑA</hc> <hc>ORIHUELA</hc> <hc>CARMELA EMPERATRIZ</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='06240042  .php'>06240042  </hc> <hc>VIDAL</hc> <hc>ROJAS</hc> <hc>MARIANELLA IVY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='06663188  .php'>06663188  </hc> <hc>VILCA</hc> <hc>DELGADO</hc> <hc>WILLIAMS SHANE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>42</hc> <hc><aref='10796076  .php'>10796076  </hc> <hc>VILCAPUMA</hc> <hc>VINCES</hc> <hc>PATRICIA BERNARDA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='03383213  .php'>03383213  </hc> <hc>VILCHERREZ</hc> <hc>VILELA</hc> <hc>DARWIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='08459715  .php'>08459715  </hc> <hc>VILLA</hc> <hc>MOROCHO</hc> <hc>CESAR AUGUSTO</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='07942626  .php'>07942626  </hc> <hc>VILLACORTA</hc> <hc>BERTOLOTTO</hc> <hc>LUIS FERNANDO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='25609588  .php'>25609588  </hc> <hc>VILLACORTA</hc> <hc>SANTAMATO</hc> <hc>LUIS ANDRES</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='80543304  .php'>80543304  </hc> <hc>VILLALOBOS</hc> <hc>VILLEGAS</hc> <hc>WILTON</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='46606605  .php'>46606605  </hc> <hc>VILLANUEVA</hc> <hc>HUAMAN</hc> <hc>FRANCISCO MIGUEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='40971221  .php'>40971221  </hc> <hc>VILLEGAS</hc> <hc>FERNANDEZ</hc> <hc>YURY JOSELINA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='000923632 .php'>000923632 </hc> <hc>VOTO</hc> <hc>.</hc> <hc>CARMINE</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='41707058  .php'>41707058  </hc> <hc>YAFAC</hc> <hc>CASTILLO</hc> <hc>CARLA VALERIE</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>43</hc> <hc><aref='09962770  .php'>09962770  </hc> <hc>YARLEQUE</hc> <hc>VILCHEZ</hc> <hc>LUIS ENRIQUE</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='09971583  .php'>09971583  </hc> <hc>YARLEQUE</hc> <hc>VILCHEZ</hc> <hc>NORMA MARIBEL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='06058263  .php'>06058263  </hc> <hc>YASUDA</hc> <hc>GOICOCHEA</hc> <hc>WALTER EDWIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='06148522  .php'>06148522  </hc> <hc>YSEKI</hc> <hc>SALAZAR</hc> <hc>SANDRA PATRICIA</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='10265508  .php'>10265508  </hc> <hc>ZAMBRANO</hc> <hc>ANGULO</hc> <hc>VICTOR HUGO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='06164675  .php'>06164675  </hc> <hc>ZAMBRANO</hc> <hc>GOICOCHEA</hc> <hc>JUAN ANTONIO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='40051853  .php'>40051853  </hc> <hc>ZANETTI</hc> <hc>GRANDEZ</hc> <hc>NICOLAS ALBERTO MARTIN</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='16727294  .php'>16727294  </hc> <hc>ZAPATA</hc> <hc>CORRALES</hc> <hc>FELIX ALBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='32102213  .php'>32102213  </hc> <hc>ZAPATA</hc> <hc>ROQUE</hc> <hc>JOSE CARLOS</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='41301023  .php'>41301023  </hc> <hc>ZARATE</hc> <hc>AGUILAR</hc> <hc>KARIN BELINDA</hc> <hc>ITALIA</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>44</hc> <hc><aref='08098554  .php'>08098554  </hc> <hc>ZARATE</hc> <hc>HERMOZA</hc> <hc>JESUS ROBERTO</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>45</hc> <hc><aref='09533788  .php'>09533788  </hc> <hc>ZARATE</hc> <hc>ROMAN</hc> <hc>MARISA CONSUELO</hc> <hc>PERÚ</hc> <hc>Ordinario Asociado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>45</hc> <hc><aref='10650280  .php'>10650280  </hc> <hc>ZAVALETA</hc> <hc>ARTEAGA</hc> <hc>MAGALI KATTY</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>45</hc> <hc><aref='06118755  .php'>06118755  </hc> <hc>ZEVALLOS</hc> <hc>DE LAS CASAS</hc> <hc>LUISA INES</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Completo</hc> </hr></p>
<p><hr><hc>45</hc> <hc><aref='41340477  .php'>41340477  </hc> <hc>ZUÑIGA</hc> <hc>ALVARADO DE LA ROSA</hc> <hc>NELIZA KELI</hc> <hc>PERÚ</hc> <hc>Ordinario Auxiliar</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>45</hc> <hc><aref='05343430  .php'>05343430  </hc> <hc>ZUÑIGA</hc> <hc>EURIBE</hc> <hc>ARTURO PAUL</hc> <hc>PERÚ</hc> <hc>Contratado</hc> <hc>Tiempo Parcial</hc> </hr></p>
<p><hr><hc>No</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(1</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(2</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(3</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(4</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(5</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(6</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(7</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>(8</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>  </hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>NO</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>DE</hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>  </hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
<p><hr><hc>  </hc> <hc><aref='          .php'>          </hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> <hc></hc> </hr></p>
?>