<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="estiloUCSS2.css" rel="stylesheet" media="screen">
<title>
</title>
</head>
<body>
<table align='center'>
<thead>
<tr>
<th colspan='2'>
<h1>PERALTA VERA, JUAN CARLOS</h1>
</th>
</tr>
</thead>
<tbody>
<tr><th><h2>Formación Académica</h2></th></tr>
<tr><th class='der' align='left'>Bachiller en Educación - Universidad Marcelino Champagnat - Lima Perú.                                                                                                                                                                                    <br>Licenciatura en Educación - Universidad Marcelino Champagnat - Lima Perú.                                                                                                                                                                                 <br>Maestría Aprendizaje y Desarrollo Humano - Universidad San Ignacio De Loyola	 - Lima Perú.                                                                                                                                                                <br>Maestría Gestión Educacional Universidad Nacional Enrique Guzmán Y Valle – La Cantuta - Lima Perú.                                                                                                                                                        <br>Diplomado en Formulación Y Evaluación De Proyectos Dentro Del Marco SNIP Universidad ESAN - Lima Perú.                                                                                                                                                    <br>Diplomado Métodos y Técnicas De Investigación - Universidad Nacional Enrique Guzmán Y Valle – La Cantuta - Lima Perú.                                                                                                                                     <br>Estudios Concluidos de Diplomado Dirección y Gestión De Instituciones Educativas - Universidad Católica Sedes Sapientiae - Lima Perú.                                                                                                                     <br>Estudios de Ofimática - Consorcio Educativo ABACO – EIGER - Callao Perú.                                                                                                                                                                                  <br>Estudios de Modificabilidad Cognitiva Estructural - The International Center For The Enhancement Of Learning Potencial - Lima Perú.                                                                                                                       <br>Estudios de Ingles - Universidad San Ignacio De Loyola.                                                                                                                                                                                                   <br>Estudios de Ingles - Universidad Nacional Enrique Guzmán Y Valle – La Cantuta.                                                                                                                                                                            <br></th></tr>
<tr><th><h2>Trayectoria Profesional</h2></th></tr>
<tr><th class = 'der' align='left'>Ministerio De Educación C.E. San Juan Bautista  de la Salle – Docente.                                                                                                                                                                                    <br>Ministerio De Educación C.E. Parroquial “Fe Y Alegría N° 43” Ventanilla – Docente.                                                                                                                                                                        <br>Ministerio De Educación C.E. Parroquial “Fe Y Alegría N° 43” Ventanilla – Director.                                                                                                                                                                       <br>Ministerio De Educación - Consultoria En Educación – En La Dirección General Educación Intercultural Bilingüe. Consultor Especialista en Pedagogía Para Evaluar a los Equipos Formuladores En La Formulación Y Evaluación de Proyectos Dentro Del Marco SN<br>Universidad Católica Del Perú - Monitor - Capacitador Del Programa Nacional De Formación Y Capacitación (PRONAFCAP).                                                                                                                                      <br>Universidad Católica Sedes Sapientiae - Investigación Servicios Prestados  a la UCSS.                                                                                                                                                                     <br>Universidad Católica Sedes Sapientiae – Docente - Servicios Prestados a la UCSS.                                                                                                                                                                          <br>Universidad Católica Sedes Sapientiae - Docente Contratado.                                                                                                                                                                                               <br>Universidad Católica Sedes Sapientiae – Docente: Seminario De Tesis I, Seminario De Tesis II en Pregrado Y Postgrado.                                                                                                                                     <br>Universidad Católica Sedes Sapientiae – Director de la Escuela de Postgrado de La UCSS.                                                                                                                                                                   <br>Universidad Católica Sedes Sapientiae – Miembro de la Asamblea y  del Consejo Universitario.	 	                                                                                                                                                           <br></th></tr>
</tbody>
</table>
<div class="boton-regresar"><a href="javascript:history.back(-1);" >Regresar</a></div>
</body>
</html>
